#!/usr/bin/env python

import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]
commit_type = ''
commit_hash = ''

if len(sys.argv) > 2:
    commit_type = sys.argv[2]

if len(sys.argv) > 3:
    commit_hash = sys.argv[3]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode("utf-8")

matches = re.match('([a-z]+)-([0-9]+)-', branch)
if matches:
  project = matches.group(1)
  issue_number = matches.group(2)

  with open(commit_msg_filepath, 'r+') as f:
    content = f.read()
    f.seek(0, 0)
    f.write("%s-%s:%s" % (project, issue_number, content))

